import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

interface PredbTeamsResponse {
  status: string;
  message: string;
  data: {
    rows: Array<{
      team: string;
      count?: number;
    }>;
  } | null;
}

export interface UpdateSceneGroupsOptions {
  sourceUrl: string;
  outputPath: string;
  minCount: number;
}

export interface UpdateSceneGroupsResult {
  outputPath: string;
  sourceUrl: string;
  groups: string[];
}

const DEFAULT_SOURCE_URL = "https://predb.ovh/api/v1/teams";
const DEFAULT_OUTPUT_PATH = "packages/core/src/generated/known-scene-groups.ts";

function parseArgs(argv: string[]): UpdateSceneGroupsOptions {
  let sourceUrl = process.env.POPCORN_QUEUE_SCENE_GROUPS_URL ?? DEFAULT_SOURCE_URL;
  let outputPath = DEFAULT_OUTPUT_PATH;
  let minCount = 1;

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--source-url") {
      sourceUrl = argv[index + 1] ?? "";
      index += 1;
      continue;
    }
    if (arg === "--output") {
      outputPath = argv[index + 1] ?? "";
      index += 1;
      continue;
    }
    if (arg === "--min-count") {
      minCount = Number(argv[index + 1] ?? "");
      index += 1;
      continue;
    }
    if (arg === "--help" || arg === "-h") {
      console.log("Usage: npm run scene-groups:update -- [--source-url URL] [--output PATH] [--min-count N]");
      process.exit(0);
    }
    throw new Error(`Unknown argument: ${arg}`);
  }

  if (!sourceUrl) throw new Error("Missing source URL.");
  if (!outputPath) throw new Error("Missing output path.");
  if (!Number.isInteger(minCount) || minCount < 1) throw new Error("--min-count must be a positive integer.");
  return { sourceUrl, outputPath, minCount };
}

function normalizeSceneGroup(group: string): string | null {
  const normalized = group.trim().toUpperCase();
  if (!/^[A-Z0-9]{2,}$/.test(normalized)) return null;
  return normalized;
}

function extractGroups(response: PredbTeamsResponse, minCount: number): string[] {
  if (response.status !== "success" || !response.data) {
    throw new Error(response.message || "Predb teams request failed.");
  }

  const groups = new Set<string>();
  for (const row of response.data.rows) {
    if (row.count !== undefined && row.count < minCount) continue;
    const group = normalizeSceneGroup(row.team);
    if (group) groups.add(group);
  }
  return [...groups].sort((left, right) => left.localeCompare(right));
}

function renderCache(sourceUrl: string, groups: string[]): string {
  const body = groups.map((group) => `  "${group}"`).join(",\n");
  return `// Generated by \`npm run scene-groups:update\`.
// Source: ${sourceUrl}
export const knownSceneGroups = [
${body}
] as const;
`;
}

function describeFetchError(error: unknown): string {
  if (!(error instanceof Error)) return String(error);
  const cause = (error as Error & { cause?: unknown }).cause;
  if (cause instanceof Error && cause.message) return `${error.message}: ${cause.message}`;
  if (cause && typeof cause === "object" && "code" in cause) return `${error.message}: ${String(cause.code)}`;
  return error.message;
}

export async function updateSceneGroups(options: UpdateSceneGroupsOptions): Promise<UpdateSceneGroupsResult> {
  let response: Response;
  try {
    response = await fetch(options.sourceUrl, {
      headers: {
        accept: "application/json",
        "user-agent": "Popcorn Queue scene group cache updater"
      }
    });
  } catch (error) {
    throw new Error(`Predb teams request failed for ${options.sourceUrl}: ${describeFetchError(error)}`);
  }

  if (!response.ok) throw new Error(`Predb teams request failed: HTTP ${response.status}`);
  const payload = (await response.json()) as PredbTeamsResponse;
  const groups = extractGroups(payload, options.minCount);
  if (groups.length === 0) throw new Error("Predb teams response did not contain any usable scene groups.");

  const outputPath = path.resolve(process.cwd(), options.outputPath);
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderCache(options.sourceUrl, groups), "utf8");
  return { outputPath, sourceUrl: options.sourceUrl, groups };
}

async function main(): Promise<void> {
  const result = await updateSceneGroups(parseArgs(process.argv.slice(2)));
  console.log(`Wrote ${result.groups.length} scene groups to ${result.outputPath}`);
}

const entrypoint = fileURLToPath(import.meta.url);
if (process.argv[1] && path.resolve(process.argv[1]) === entrypoint) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
